package MAIN;

import User.NewJFrame;
import admin.adlogin;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;
import java.awt.event.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class first extends javax.swing.JFrame {

      PreparedStatement prp = null;
    ResultSet rs = null;
    Connection con = null;
       DefaultTableModel df = new DefaultTableModel();
       String t4,t5,t6,t7;
   
    public first() {
        initComponents();
        ImageIcon ic = new ImageIcon(getClass().getResource("/ars/ic1.png"));
        this.setIconImage(ic.getImage());
        this.setTitle("ARS");
        nepan.setVisible(false);  
    this.setSize(1800,1071);
    this.setLocationRelativeTo(null);
    Border l11 = BorderFactory.createMatteBorder(1, 1, 0, 1, Color.white);
   // Border adll = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        hb.setBorder(l11);
     //   adl.setBorder(adll);
       al.setBackground(new Color(255,204,153));
        //cu.setBorder(adll);
        jPanel3.setBackground(new Color(0,0,0,90));
        fb.setBackground(new Color(0,0,0,0));
        hb.setBackground(new Color(1,1,1,1));
        lb.setBackground(new Color(0,0,0,0));
        nepan.setBackground(new Color(240,240,240,100));
         // adl.setBackground(new Color(1,1,1,1));
        jPanel2.setBackground(new Color(0,0,0,30));
        T.start();
    }
     public String week_day()
    {
    DateFormat df = new SimpleDateFormat("dd/MM/YYYY");
 Date cdate = depdate.getDate();
 String ds =(String) df.format(cdate);
    SimpleDateFormat format1=new SimpleDateFormat("dd/MM/yyyy");
  Date dt1;
  String finalDay = null;
        try {
            dt1 = format1.parse(ds);
            DateFormat format2=new SimpleDateFormat("EEEE"); 
  finalDay=format2.format(dt1);
  //JOptionPane.showMessageDialog(null,"Date: "+ds+"\nWeek of the Day is: "+finalDay);
        } catch (ParseException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
  return finalDay;
    }
    public String durn(String src,String dest)
    {
        long hr = 0;
        String drn;
        try
 {
		SimpleDateFormat format = new SimpleDateFormat("HH:mm:ss");
		Date date1 = format.parse(src);
		Date date2 = format.parse(dest);
		long difference = date2.getTime() - date1.getTime();
		 hr =((difference/1000)/3600);
      
 }
 catch (Exception e)
 {
     JOptionPane.showMessageDialog(null,"Time Error"+e); 
 }
        int h = (int) hr;
        if( h<=0)
            return "1h";
        else
        {
            drn = Integer.toString(h)+"h";
        return drn;
        }
        
    }
    public boolean chkdate()
    {
                  DateFormat dbs = new SimpleDateFormat("YYYY-MM-dd");
 Date ddb = depdate.getDate();
 String db =(String) dbs.format(ddb);
 Date cdbs = new Date();
 String cdb = dbs.format(cdbs);
 String d1[] =db.split("-");
 String d2[] =cdb.split("-");
 int x[] = new int[3];
 int y[] = new int[3];
 int s1=0,s2=0;
 for(int i =0;i<3;i++)
 {
     x[i]=Integer.parseInt(d1[i]);
     y[i]=Integer.parseInt(d2[i]);
 s1=(s1*100)+x[i];
 s2=(s2*100)+y[i];
 }
 int sum =s1-s2;
 if(sum>=0)
        return true;
 else
     return false;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nepan = new javax.swing.JPanel();
        cu = new javax.swing.JLabel();
        al = new javax.swing.JLabel();
        fb = new javax.swing.JToggleButton();
        lb = new javax.swing.JToggleButton();
        hb = new javax.swing.JToggleButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        adl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        srccombo = new javax.swing.JComboBox();
        destcombo = new javax.swing.JComboBox();
        depdate = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();

        jDialog1.getContentPane().setLayout(null);

        jPanel4.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Flight Number", "Flight Name", "Source", "Destination", "Arival", "Departure", "Duration", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 640, 210);

        jButton2.setText("Okay");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(260, 230, 106, 47);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ars/plane-3093859_640.jpg"))); // NOI18N
        jPanel4.add(jLabel10);
        jLabel10.setBounds(0, 1, 640, 300);

        jDialog1.getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 640, 290);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setLayout(null);

        cu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cu.setText("Contact US");
        cu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cuMouseExited(evt);
            }
        });

        al.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        al.setText("Admin Login");
        al.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                alMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                alMouseExited(evt);
            }
        });

        javax.swing.GroupLayout nepanLayout = new javax.swing.GroupLayout(nepan);
        nepan.setLayout(nepanLayout);
        nepanLayout.setHorizontalGroup(
            nepanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nepanLayout.createSequentialGroup()
                .addGroup(nepanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(al, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(cu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        nepanLayout.setVerticalGroup(
            nepanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nepanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(al, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        jPanel1.add(nepan);
        nepan.setBounds(0, 30, 100, 90);

        fb.setForeground(new java.awt.Color(255, 255, 255));
        fb.setText("FAQ");
        fb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fbMouseExited(evt);
            }
        });
        fb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fbActionPerformed(evt);
            }
        });
        jPanel1.add(fb);
        fb.setBounds(120, 120, 100, 40);

        lb.setForeground(new java.awt.Color(255, 255, 255));
        lb.setText("LOGIN");
        lb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbMouseExited(evt);
            }
        });
        lb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbActionPerformed(evt);
            }
        });
        jPanel1.add(lb);
        lb.setBounds(220, 120, 100, 40);

        hb.setForeground(new java.awt.Color(255, 255, 255));
        hb.setSelected(true);
        hb.setText("HOME");
        hb.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        hb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hbMouseExited(evt);
            }
        });
        hb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hbActionPerformed(evt);
            }
        });
        jPanel1.add(hb);
        hb.setBounds(20, 120, 100, 40);

        jLabel12.setFont(new java.awt.Font("Sylfaen", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(" - ");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });
        jPanel1.add(jLabel12);
        jLabel12.setBounds(1670, 10, 60, 40);

        jLabel11.setFont(new java.awt.Font("Sylfaen", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("X");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });
        jPanel1.add(jLabel11);
        jLabel11.setBounds(1740, 10, 45, 50);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("AIRLINE RESERVATION SYSTEM");
        jLabel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255))));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(600, 70, 770, 60);

        adl.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        adl.setForeground(new java.awt.Color(255, 255, 255));
        adl.setText("Admin");
        adl.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                adlFocusLost(evt);
            }
        });
        adl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adlMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adlMouseExited(evt);
            }
        });
        jPanel1.add(adl);
        adl.setBounds(10, 0, 70, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ars/pexels-photo-723240.jpeg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1800, 160);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1800, 160);

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jPanel3.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ars/1.jpeg"))); // NOI18N
        jLabel9.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel9);
        jLabel9.setBounds(10, 10, 980, 710);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(740, 260, 1000, 730);

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("From");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("To");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Departure Date");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Passnger");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jSpinner1.setName(""); // NOI18N
        jSpinner1.setValue(1);
        jSpinner1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSpinner1MouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BOOK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel8.setText("Book Flight");

        srccombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT SOURCE", "Bangalore", "Bagdogra", "Bhubaneswar", "Chandigarh", "Chennai", "Delhi", "Goa", "Hyderabad", "Mumbai", "Patna", "Srinagar" }));
        srccombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srccomboActionPerformed(evt);
            }
        });

        destcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT DESTINATION", "Bangalore", "Bagdogra", "Bhubaneswar", "Chandigarh", "Chennai", "Delhi", "Goa", "Hyderabad", "Mumbai", "Patna", "Srinagar" }));
        destcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destcomboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(destcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(srccombo, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depdate, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(srccombo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(destcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(80, 400, 550, 460);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ars/aircraft-landing-reach-injection-47044.jpeg"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-30, 0, 1840, 1070);

        pack();
    }// </editor-fold>//GEN-END:initComponents
int z=0;
Icon a =new ImageIcon(getClass().getResource("/ars/1.jpeg"));
Icon b =new ImageIcon(getClass().getResource("/ars/2f.jpeg"));//ImageIcon("/ars/2.jpeg");
Icon c =new ImageIcon(getClass().getResource("/ars/3.jpeg"));//ImageIcon("/ars/3.jpeg");
Icon d =new ImageIcon(getClass().getResource("/ars/4.jpeg"));///ImageIcon("/ars/4.jpeg");
Icon m =new ImageIcon(getClass().getResource("/ars/5.jpeg"));//ImageIcon("/ars/5.jpeg");
Timer T =new Timer(800,new ActionListener(){

        @Override
        public void actionPerformed(ActionEvent e) {
            z++;
            switch(z)
            {
                case 1: jLabel9.setIcon(a);
                    break;
                case 2: jLabel9.setIcon(b);
                    break;
                case 3: jLabel9.setIcon(c);
                    break;
                case 4: jLabel9.setIcon(d);
                    break;
                case 5: jLabel9.setIcon(m);
                    break;
                    
            }
            if(z==5)
            {
                z=0;
            }
         //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    
});
    private void jSpinner1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinner1MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinner1MouseClicked

    private void fbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fbMouseEntered
        fb.setBackground(new Color(0,0,0,1));
       hb.setBackground(new Color(1,1,1,1));
        lb.setBackground(new Color(0,0,0,0));
        // TODO add your handling code here:
    }//GEN-LAST:event_fbMouseEntered

    private void fbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fbMouseExited
        fb.setBackground(new Color(0,0,0,0));
        // TODO add your handling code here:
    }//GEN-LAST:event_fbMouseExited

    private void fbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fbActionPerformed
        new FAQ().setVisible(true);
        this.setVisible(false);
        new login().setVisible(false);
        new register().setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_fbActionPerformed

    private void lbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMouseEntered
        lb.setBackground(new Color(0,0,0,1));
        hb.setBackground(new Color(1,1,1,1));
        fb.setBackground(new Color(0,0,0,0));
        // TODO add your handling code here:
    }//GEN-LAST:event_lbMouseEntered

    private void lbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMouseExited
        lb.setBackground(new Color(0,0,0,0));
        // TODO add your handling code here:
    }//GEN-LAST:event_lbMouseExited

    private void lbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbActionPerformed
        new login().setVisible(true);
        new FAQ().setVisible(false);
        this.setVisible(false);
        new register().setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_lbActionPerformed

    private void hbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hbMouseEntered
        hb.setBackground(new Color(0,0,0,1));
        // TODO add your handling code here:
    }//GEN-LAST:event_hbMouseEntered

    private void hbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hbMouseExited
        hb.setBackground(new Color(0,0,0,1));
        // TODO add your handling code here:
    }//GEN-LAST:event_hbMouseExited

    private void hbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hbActionPerformed
        this.setVisible(true);
        new FAQ().setVisible(false);
        new login().setVisible(false);
        new register().setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_hbActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        this.setState(JFrame.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        Border l11 = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel12.setBorder(l11);   // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        Border l11 = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(0,0,0,0));
        jLabel12.setBorder(l11);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        Border l11 = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel11.setBorder(l11);   // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        Border l11 = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(0,0,0,0));
        jLabel11.setBorder(l11);   // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseExited

    private void adlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adlMouseEntered
       Border l11 = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        adl.setBorder(l11);  // TODO add your handling code here:
    }//GEN-LAST:event_adlMouseEntered

    private void adlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adlMouseExited
       Border l11 = BorderFactory.createMatteBorder(0, 0, 0, 0, Color.black);
        adl.setBorder(l11);  // TODO add your handling code here:
    }//GEN-LAST:event_adlMouseExited

    private void adlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adlMouseClicked
nepan.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_adlMouseClicked

    private void alMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alMouseClicked
     nepan.setVisible(false);
        //JOptionPane.showMessageDialog(null,"Hello Admin");
     this.setVisible(false);
     new adlogin().setVisible(true);
        
     // TODO add your handling code here:
    }//GEN-LAST:event_alMouseClicked

    private void alMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alMouseEntered
Border l11 = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        al.setBorder(l11);        // TODO add your handling code here:
    }//GEN-LAST:event_alMouseEntered

    private void alMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alMouseExited
Border l11 = BorderFactory.createMatteBorder(0, 0, 0, 0, Color.black);
        al.setBorder(l11);        // TODO add your handling code here:
    }//GEN-LAST:event_alMouseExited

    private void cuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuMouseClicked
     nepan.setVisible(false); 
        JOptionPane.showMessageDialog(null,"Need Help? \nWe're here 24X7\n Phone Number: 9249404612,8113123384\n E-mail: 1hk17cs102@hkbk.edu.in, 1hk17cs111@hkbk.edu.in ");
       // JOptionPane.showConfirmDialog(null, "Need Help? \nWe're here on bussinus hours\n Phone Number: 9113123382, 8249404614\n E-mail: 1hk17cs111@hkbk.edu.in, 1hk17cs102@hkbk.edu.in ");
          // TODO add your handling code here:
    }//GEN-LAST:event_cuMouseClicked

    private void cuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuMouseEntered
       Border l11 = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        cu.setBorder(l11); // TODO add your handling code here:
    }//GEN-LAST:event_cuMouseEntered

    private void cuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuMouseExited
     Border l11 = BorderFactory.createMatteBorder(0, 0, 0, 0, Color.black);
        cu.setBorder(l11);   // TODO add your handling code here:
    }//GEN-LAST:event_cuMouseExited

    private void adlFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adlFocusLost
        nepan.setVisible(false);  // TODO add your handling code here:
    }//GEN-LAST:event_adlFocusLost

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
 nepan.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
 nepan.setVisible(false); 
 // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
 nepan.setVisible(false); 
 // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
 nepan.setVisible(false); 
 // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
 nepan.setVisible(false); 
 // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String nsrc = null;
        String ndest = null;
      String srcd = srccombo.getSelectedItem().toString();
      String dest = destcombo.getSelectedItem().toString();
      boolean vdate = chkdate();
      if(srcd.equals(dest)||srcd.equals("SELECT SOURCE")||dest.equals("SELECT DESTINATION")||srcd.equals(dest))
      {
          JOptionPane.showMessageDialog(null,"Invalid Area Selection");
      }
      else
      {
      ;
          if(!vdate)
          JOptionPane.showMessageDialog(null,"Invalid Date Selection");
          else
          {
             
          }
              
                        Object columns[] = {"Flight Number", "Flight Company", "Source", "Destination", "Arrival", "Departure","Duration","Fare"};
        df.setColumnIdentifiers(columns);
        jTable1.setModel(df);
        String t1,t2;
      
              String wk= week_day();
              try
              {
           con = DriverManager.getConnection("jdbc:mysql://localhost:3306/arsystem", "root","bourbon5"); 
            String sql = "select * from area a, aircraft f where a.wk_day= ? and a.src=? and a.dest=? and a.flt_no =f.f_no";
        
    
          
           prp =con.prepareStatement(sql);
           prp.setString(1,wk);
           prp.setString(2,srcd);
           prp.setString(3,dest);
          
        //dispose();
              df.getDataVector().removeAllElements();
              Object columnData[]= new Object[8];
              rs =prp.executeQuery();
       while(rs.next())
              {
                  
                  t4=rs.getString("f_no");
                  columnData[0] =t4;
                  t5=rs.getString("f_name");
                columnData[1] = t5;
                t6=rs.getString("src");
                columnData[2] = t6;
                t7=rs.getString("dest");
                columnData[3] = t7;
                t1=rs.getString("arrival");
                t2=rs.getString("depature");
                columnData[4] = t1;
                columnData[5] = t2;
                String t3 =durn(t1,t2); 
                columnData[6] = t3;
              //  JOptionPane.showMessageDialog(null,"List!\n"+" "+t5+" "+t6+" "+t7+" "+t1+" "+t2+" "+t3);
                columnData[7] = rs.getString("fare");            
                df.addRow(columnData); 
       
              }
       jDialog1.setVisible(true);
       jDialog1.setSize(630,340);
       jDialog1.setLocationRelativeTo(null);
       jScrollPane1.setBackground(new Color(0,0,0,50));
            jTable1.setBackground(new Color(0,0,0,50));
       con.close();
              }
              catch(SQLException e)
              {
                  JOptionPane.showMessageDialog(null,"ERROR:-\n"+e);
              }
              }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void srccomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srccomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srccomboActionPerformed

    private void destcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destcomboActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jDialog1.setVisible(false);
        this.setVisible(false);
new login().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new first().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adl;
    private javax.swing.JLabel al;
    private javax.swing.JLabel cu;
    private com.toedter.calendar.JDateChooser depdate;
    private javax.swing.JComboBox destcombo;
    private javax.swing.JToggleButton fb;
    private javax.swing.JToggleButton hb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton lb;
    private javax.swing.JPanel nepan;
    private javax.swing.JComboBox srccombo;
    // End of variables declaration//GEN-END:variables
}
