/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import static admin.info.bk;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;




public class dead extends javax.swing.JFrame {

 PreparedStatement prp = null;
    ResultSet rs = null;
    Connection con = null;
    /**
     * Creates new form dead
     */
    public dead() {
        initComponents();
        this.setSize(640,430);
        this.setLocationRelativeTo(null);
         ImageIcon ic = new ImageIcon(getClass().getResource("/ars/ic1.png"));
        this.setIconImage(ic.getImage());
        this.setTitle("ARS");
        load();
    }
    
    public void load()
    {
        fno.setText("");
        cmp.setText(null);
        try
    {
    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/arsystem", "root","bourbon5");
    String sql="select f_no from aircraft";
    prp =con.prepareStatement(sql);
    rs = prp.executeQuery();
    fltcmbo.removeAllItems();
    fltcmbo.addItem("Select Flt_no");
    while(rs.next())
    {
        String srcc=rs.getString("f_no");
        fltcmbo.addItem(srcc);
    }
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(null,"ERROR:\n"+e);
    }
    }
public void add()
{
    String fn =fno.getText();
    String cm = cmp.getText();
    String sql ="insert into aircraft (f_no,f_name) values('"+fn+"', '"+cm+"')";
    try
    {
          con = DriverManager.getConnection("jdbc:mysql://localhost:3306/arsystem", "root","bourbon5");
          prp = con.prepareStatement(sql);
          int count = prp.executeUpdate();
          if(count>0)
          {
              JOptionPane.showMessageDialog(null,"New Flight is Added");
              load();
          }
          else
              JOptionPane.showMessageDialog(null,"Flight Insertion Failed");
    }
    catch(SQLException e)
    {
         JOptionPane.showMessageDialog(null,"ERROR: "+e);
    }
    
}

public void delete()
{
    String selfno =fltcmbo.getSelectedItem().toString();
    if(selfno.equals("Select Flt_no"))
    {
     JOptionPane.showMessageDialog(null,"Invalid Flight Number ");   
    }
    else
    {
        try
        {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/arsystem", "root","bourbon5");
        String sql1 ="Delete from aircraft where f_no = '"+selfno+"'";
         prp =con.prepareStatement(sql1);
          int count = prp.executeUpdate();
          if(count>0)
          {
              JOptionPane.showMessageDialog(null,"Flight Deleted Successfully");   
              load();
          }
          else
          {
              JOptionPane.showMessageDialog(null,"Flight Deletion Failed");
          }
          
        }
         catch(SQLException e)
    {
         JOptionPane.showMessageDialog(null,"ERROR: "+e);
    }
        
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        fltcmbo = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        ad = new javax.swing.JRadioButton();
        de = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        cmp = new javax.swing.JTextField();
        fno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        fltcmbo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Flt_no" }));
        getContentPane().add(fltcmbo);
        fltcmbo.setBounds(310, 240, 142, 22);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 320, 633, 20);

        buttonGroup1.add(ad);
        ad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ad.setForeground(new java.awt.Color(255, 255, 255));
        ad.setText("ADD");
        getContentPane().add(ad);
        ad.setBounds(20, 110, 80, 31);

        buttonGroup1.add(de);
        de.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        de.setForeground(new java.awt.Color(255, 255, 255));
        de.setText("DELETE");
        getContentPane().add(de);
        de.setBounds(20, 240, 110, 31);

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));
        jPanel1.setLayout(null);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ars/left-arrow.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 10, 64, 64);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("ADD/DELETE Flight");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(160, 10, 370, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 630, 80);

        jButton1.setText("Add/Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 340, 170, 25);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 210, 633, 20);
        getContentPane().add(cmp);
        cmp.setBounds(490, 110, 120, 40);
        getContentPane().add(fno);
        fno.setBounds(220, 110, 120, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Flight Number");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 110, 110, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Company Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(360, 116, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Select Flight Number");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 240, 160, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ars/clouds-4589586_640.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1, -4, 630, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(ad.isSelected())
{
    add();
}
else if(de.isSelected())
{
    delete();
}
else
    JOptionPane.showMessageDialog(null,"Please Select Any one Option");
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.setVisible(false);
         bk();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        ImageIcon ic = new ImageIcon(getClass().getResource("/ars/left-arrow-in-circular-button-black-symbol.png")) ;
        jLabel4.setIcon(ic);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        ImageIcon ic = new ImageIcon(getClass().getResource("/ars/left-arrow.png"));
        jLabel4 .setIcon(ic);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseExited

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dead().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ad;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cmp;
    private javax.swing.JRadioButton de;
    private javax.swing.JComboBox fltcmbo;
    private javax.swing.JTextField fno;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
